package com.shanergy.bprev.service;

import com.shanergy.bprev.dto.DisciplineDtos;
import com.shanergy.bprev.model.DisciplinaryFlag;
import com.shanergy.bprev.model.DisciplinaryRule;
import com.shanergy.bprev.model.Hazard;
import com.shanergy.bprev.model.Risk;
import com.shanergy.bprev.model.User;
import com.shanergy.bprev.repository.DisciplinaryFlagRepository;
import com.shanergy.bprev.repository.DisciplinaryRuleRepository;
import com.shanergy.bprev.repository.HazardRepository;
import com.shanergy.bprev.repository.RiskRepository;
import com.shanergy.bprev.repository.UserRepository;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

@SpringBootTest
@Transactional
class DisciplineServiceTest {

    @Autowired DisciplineService disciplineService;
    @Autowired DisciplinaryRuleRepository ruleRepository;
    @Autowired DisciplinaryFlagRepository flagRepository;
    @Autowired RiskRepository riskRepository;
    @Autowired HazardRepository hazardRepository;
    @Autowired UserRepository userRepository;
    @Autowired NotificationService notificationService;
    @Autowired AuditService auditService;

    private User admin;

    @BeforeEach
    void setup() {
        admin = userRepository.findByUsername("admin").orElseThrow();
        notificationService.drainDelivered();
        auditService.getEventsAndClear();
        flagRepository.deleteAll();
        ruleRepository.deleteAll();
    }

    @Test
    void createRuleAndEvaluate_autoGeneratesFlag() {
        DisciplineDtos.RuleRequest ruleRequest = new DisciplineDtos.RuleRequest();
        ruleRequest.setName("重大隐患黄牌");
        ruleRequest.setOrganizationLevel("MINE");
        ruleRequest.setMetricType("HAZARD_MAJOR_COUNT");
        ruleRequest.setThresholdWindowDays(30);
        ruleRequest.setThresholdValue(1);
        ruleRequest.setSeverity("YELLOW");
        ruleRequest.setNotificationChannels(List.of("SMS", "APP"));
        DisciplinaryRule rule = disciplineService.createRule(ruleRequest, admin);

        UUID orgId = UUID.fromString("11111111-1111-1111-1111-111111111111");
        Risk risk = new Risk();
        risk.setDescription("重大风险");
        risk.setLevel("重大");
        risk.setResponsibleOrgId(orgId);
        riskRepository.save(risk);

        Hazard hazard = new Hazard();
        hazard.setDescription("重大隐患");
        hazard.setStatus("整改中");
        hazard.setLevel("重大");
        hazard.setReporterId(admin.getUserId());
        hazard.setReportedAt(OffsetDateTime.now());
        hazard.setRiskId(risk.getRiskId());
        hazardRepository.save(hazard);

        var results = disciplineService.evaluateActiveRules();
        Assertions.assertThat(results).isNotEmpty();
        DisciplineDtos.EvaluationResult summary = results.stream()
                .filter(r -> r.getRuleId().equals(rule.getRuleId()))
                .findFirst()
                .orElseThrow();
        Assertions.assertThat(summary.getTriggeredCount()).isEqualTo(1);

        List<DisciplinaryFlag> flags = flagRepository.findByOrganizationId(orgId);
        Assertions.assertThat(flags).hasSize(1);
        DisciplinaryFlag flag = flags.get(0);
        Assertions.assertThat(flag.isAutoGenerated()).isTrue();
        Assertions.assertThat(flag.getRuleId()).isEqualTo(rule.getRuleId());
        Assertions.assertThat(flag.getSeverity()).isEqualTo("YELLOW");
        Assertions.assertThat(flag.getStatus()).isEqualTo("ACTIVE");

        var delivered = notificationService.drainDelivered();
        Assertions.assertThat(delivered).hasSize(1);
        var record = delivered.get(0);
        Assertions.assertThat(record.getChannels()).containsExactly("SMS", "APP");
        Assertions.assertThat(record.getContext().get("ruleId")).isEqualTo(rule.getRuleId().toString());

        var auditEvents = auditService.getEventsAndClear();
        Assertions.assertThat(auditEvents.stream().map(e -> e.action))
                .contains("discipline.rule.create", "discipline.flag.auto");
    }

    @Test
    void manualFlagLifecycle() {
        DisciplineDtos.FlagRequest request = new DisciplineDtos.FlagRequest();
        UUID orgId = UUID.fromString("11111111-1111-1111-1111-111111111111");
        request.setOrganizationId(orgId);
        request.setSeverity("RED");
        request.setReason("重复超标");
        request.setDeadline(java.time.LocalDate.now().plusDays(7));

        DisciplinaryFlag flag = disciplineService.createFlag(request, admin);
        Assertions.assertThat(flag.getFlagId()).isNotNull();
        Assertions.assertThat(flag.getStatus()).isEqualTo("ACTIVE");
        Assertions.assertThat(flag.isAutoGenerated()).isFalse();
        Assertions.assertThat(flag.getCreatedBy()).isEqualTo(admin.getUserId());

        DisciplineDtos.ResolveRequest resolveRequest = new DisciplineDtos.ResolveRequest();
        resolveRequest.setResolutionNote("整改通过");
        disciplineService.resolveFlag(flag.getFlagId(), resolveRequest, admin);

        DisciplinaryFlag resolved = flagRepository.findById(flag.getFlagId()).orElseThrow();
        Assertions.assertThat(resolved.getStatus()).isEqualTo("RESOLVED");
        Assertions.assertThat(resolved.getResolutionNote()).isEqualTo("整改通过");
        Assertions.assertThat(resolved.getResolvedAt()).isNotNull();

        var auditEvents = auditService.getEventsAndClear();
        Assertions.assertThat(auditEvents.stream().map(e -> e.action))
                .contains("discipline.flag.create", "discipline.flag.resolve");
    }
}
